language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py install

script:
  - coverage run --source=pesigcheck --branch -m unittest

after_success:
  - coverage report
  - codecov
