language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py install

script:
  - coverage run --source=signify --branch -m unittest

after_success:
  - coverage report
  - codecov
